-- 면접 답변 테이블 (기존 구조 유지)
CREATE TABLE IF NOT EXISTS interview_answer (
    INTV_ANS_ID BIGINT NOT NULL AUTO_INCREMENT,
    INTV_Q_ASSIGN_ID BIGINT NOT NULL,
    ANS_TXT TEXT DEFAULT NULL,
    RGS_DTM TIMESTAMP NULL DEFAULT NULL,
    USER_ID VARCHAR(100) DEFAULT NULL COMMENT '사용자 ID',
    QUESTION_NUM INT DEFAULT NULL COMMENT '질문 번호',
    ANSWER_TEXT TEXT DEFAULT NULL COMMENT '답변 내용',
    UPD_DTM TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시',
    PRIMARY KEY (INTV_ANS_ID),
    KEY INTV_Q_ASSIGN_ID (INTV_Q_ASSIGN_ID)
) ENGINE=InnoDB AUTO_INCREMENT=10010 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- 답변 평가 테이블
CREATE TABLE IF NOT EXISTS answer_score (
    ANS_SCORE_ID BIGINT NOT NULL COMMENT '답변 평가 ID',
    INTV_ANS_ID BIGINT NOT NULL COMMENT '면접 답변 ID',
    ANS_SUMMARY TEXT NULL COMMENT '답변 요약',
    EVAL_SUMMARY TEXT NULL COMMENT '전체 평가 요약',
    INCOMPLETE_ANSWER BOOLEAN NULL DEFAULT FALSE COMMENT '미완료 여부',
    INSUFFICIENT_CONTENT BOOLEAN NULL DEFAULT FALSE COMMENT '내용 부족 여부',
    SUSPECTED_COPYING BOOLEAN NULL DEFAULT FALSE COMMENT '커닝 의심 여부',
    SUSPECTED_IMPERSONATION BOOLEAN NULL DEFAULT FALSE COMMENT '대리 시험 의심 여부',
    RGS_DTM TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록 일시',
    UPD_DTM TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시',
    PRIMARY KEY (ANS_SCORE_ID),
    INDEX idx_intv_ans_id (INTV_ANS_ID),
    CONSTRAINT answer_score_ibfk_1 
        FOREIGN KEY (INTV_ANS_ID) REFERENCES interview_answer(INTV_ANS_ID)
        ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='답변 평가';

-- 답변 항목별 평가 결과 테이블
CREATE TABLE IF NOT EXISTS answer_category_result (
    ANS_CAT_RESULT_ID BIGINT NOT NULL COMMENT '답변 항목별 평가 ID',
    EVAL_CAT_CD VARCHAR(20) NOT NULL COMMENT '평가 항목 코드',
    ANS_SCORE_ID BIGINT NOT NULL COMMENT '답변 평가 ID',
    ANS_CAT_SCORE DOUBLE NULL COMMENT '항목별 점수',
    STRENGTH_KEYWORD TEXT NULL COMMENT '강점 키워드',
    WEAKNESS_KEYWORD TEXT NULL COMMENT '약점 키워드',
    RGS_DTM TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록 일시',
    UPD_DTM TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시',
    PRIMARY KEY (ANS_CAT_RESULT_ID),
    INDEX idx_ans_score_id (ANS_SCORE_ID),
    INDEX idx_eval_cat_cd (EVAL_CAT_CD),
    CONSTRAINT fk_answer_category_result_ans_score_id 
        FOREIGN KEY (ANS_SCORE_ID) REFERENCES answer_score(ANS_SCORE_ID)
        ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='답변 항목별 평가 결과';

